### PR TITLE
Replace IRC since mostly unused + Freenode fiasco

### PR DESCRIPTION
**Pull request by xeraa**
Thanks to @jstrassb for finding this one.

Pull request acceptance prerequisites:

- [x] Signed the [CLA](https://www.elastic.co/contributor-agreement/) (if not already signed)
- [x] Rebased/up-to-date with base branch
- [ ] Tests pass
- [ ] Updated CHANGELOG.md with patch notes (if necessary)
- [ ] Updated CONTRIBUTORS (if attribution is requested)

### CODE REVIEW

**Comment by ghoneycutt** [comment]
This is managed by VP so it should use our contact info.

**Comment by smortex** [comment]
@xeraa +1 for splitting

The info in the footer of https://voxpupuli.org/ should be fine I think.

**Comment by bastelfreak** [comment]
we did the cleanup in https://github.com/voxpupuli/puppet-elasticsearch/pull/1143

**Comment by xeraa** [comment]
Thank you!

**Pull request closed without merging**
