### PR TITLE
Snapshot lifecycle policy tests

### PR DESCRIPTION
**Pull request by bartjanssens92**
In this pull request I am adding the requested tests for the snapshot_lifecycle_policy changes made by tmanninger in PULL #1084 .

Pull request acceptance prerequisites:

- [x] Signed the [CLA](https://www.elastic.co/contributor-agreement/) (if not already signed)
- [x] Rebased/up-to-date with base branch
- [ ] Tests pass
- [ ] Updated CHANGELOG.md with patch notes (if necessary)
- [ ] Updated CONTRIBUTORS (if attribution is requested)

### CODE REVIEW

**Comment by bartjanssens92** [comment]
Could I have some pointers to get this Pull request merged please?

**Comment by fatmcgav** [comment]
@bartjanssens92 Thank you for picking up the old PR. 

Firstly, I've just merged a load of changes to `master` for supporting `7.x`, so this will need a rebase/merge. 

I'll have a more in-depth review in due course though...

**Comment by bartjanssens92** [comment]
@fatmcgav I've squashed the typo and syntax fixes into one commit and rebased on master. Looking forward to that more in-depth review :)

**Comment by fatmcgav** [comment]
@bartjanssens92 Thanks for updating from master.

It looks like `rubocop` doesn't like the `generate_body` method.
However it looks sane to me, so think it's easiest to disable the checks for this method:

```ruby
# rubocop:disable Metrics/CyclomaticComplexity
# rubocop:disable Metrics/PerceivedComplexity
def generate_body
...
end
# rubocop:enable Metrics/PerceivedComplexity
# rubocop:enable Metrics/CyclomaticComplexity

```

**Comment by bartjanssens92** [comment]
Just a quick status update, I'm getting closer to finishing the tests but this was given a lower prio. Back on it now.

**Comment by smortex** [comment]
Close in favor of #1164 (please test this PR and report if working as expected if you can).  Thanks!

**Pull request closed without merging**
