### PR TITLE
Add support for ILM policies

### LINKED ISSUE #1038: Support for index lifecycle management (ILM)
Ability to update and maintain lifecycle policies
https://www.elastic.co/guide/en/elasticsearch/reference/6.8/index-lifecycle-management-api.html

https://www.elastic.co/guide/en/elasticsearch/reference/6.8/index-lifecycle-management.html

### PR DESCRIPTION
**Pull request by NITEMAN**
#### Pull Request (PR) description
Add support for managing ILM policies

Work is based on #1146 and makes #1103 obsolete

#### This Pull Request (PR) fixes the following issues
Fixes #1038

### CODE REVIEW

**Comment by usp-rol** [comment]
That feature is actually missed at our side too and would be greatly appreciated!

**Comment by NITEMAN** [comment]
@usp-rol for what it's worth we have been using this code (along with #1164 & #1146) for months in several clients without any issues

**Comment by usp-rol** [comment]
> @usp-rol for what it's worth we have been using this code (along with #1164 & #1146) for months in several clients without any issues

great we aim to do the same (puppet managed environment being migrated to ILM). as I can see this work is basically ready to be integrated (as long as someone having write permission is willing to do so), is that correct?

would be great to see that missing piece integrated into the module.

**Comment by weastur** [comment]
+1 
It would be great to see it merged and released.

**Pull request merged**
