### PR TITLE
Fix rubocop LineLength # see https://rubocop.readthedocs.io/en/latest…

### PR DESCRIPTION
**Pull request by thomas-merz**
…/cops_layout/#layoutlinelength

Pull request acceptance prerequisites:

- [x] Signed the [CLA](https://www.elastic.co/contributor-agreement/) (if not already signed)
- [x] Rebased/up-to-date with base branch
- [x] Tests pass
- [-] Updated CHANGELOG.md with patch notes (if necessary)
- [-] Updated CONTRIBUTORS (if attribution is requested)

### CODE REVIEW

**Comment by thomas-merz** [comment]
Hi, I read and signed the above mentioned agreement already!?

**Comment by emanuil-tolev** [comment]
> Hi, I read and signed the above mentioned agreement already!?

Hi @thomas-merz . Everything seems to be fine with your Contributor License Agreement now. 

Screen Shot 2020-04-06 at 13 15 58

**Comment by emanuil-tolev** [comment]
I can't help with reviewing the PR, will leave that up to the repo maintainers :). Thanks for reaching out to get the CLA sorted.

**Comment by alexjfisher** [comment]
This is incorrect for the version of rubocop used by this project.
See the build logs. https://travis-ci.org/github/elastic/puppet-elasticsearch/jobs/670673582#L349

**Comment by ghoneycutt** [comment]
Closing as this will be fixed with modulesync in https://github.com/voxpupuli/puppet-elasticsearch/pull/1125

**Pull request closed without merging**
