### PR TITLE
Add support for ILM policies and indices

### PR DESCRIPTION
**Pull request by joshperry**
Trying to upstream this addition to manage ILM policies and indices.

Love some input as I'm not sure if this is the best method to accomplish this. Also, now realize I was working on an old version of this module which didn't have tests so I'm going to need to add those.

Going to need to get my employer to sign the CLA (or assign me copyright so I can).

Fixes: #1038

Pull request acceptance prerequisites:

- [ ] Signed the [CLA](https://www.elastic.co/contributor-agreement/) (if not already signed)
- [x] Rebased/up-to-date with base branch
- [ ] Tests pass
- [ ] Updated CHANGELOG.md with patch notes (if necessary)
- [ ] Updated CONTRIBUTORS (if attribution is requested)

### CODE REVIEW

**Comment by joshperry** [comment]
Paid all my rubocop tickets. I'll work on some tests tomorrow.

**Comment by fatmcgav** [comment]
@joshperry Thank you for the contribution - This looks like a very good start. 

As you say, some tests would be awesome. 
Also, I've just pushed a load of changes to the `master` branch, so this will need a rebase/merge :) 

Finally, we will need to have a signed CLA before we can accept this contribution. 

Thanks again.

**Comment by ghoneycutt** [comment]
This needs tests to be merged. The minimum would be some acceptance testing.

**Comment by smortex** [comment]
Close in favor of #1163 (please test this PR and report if working as expected if you can).  Thanks!

**Pull request closed without merging**
