### PR TITLE
Modulesync 5.1.0

### PR DESCRIPTION
**Pull request by smortex**

### CODE REVIEW

**Comment by smortex** [comment]
> I usually pin on the current version as lowest supported one. 1.0.0 will probaby not work.

It used to be like this at some point in the past (e.g. 040dcd94d34d2b570af73a190f32dbbd98d12881, 2dd4af0ac26ccee1f65398a1b6cac48bc2f9bb90).  In fact it is only required for the acceptance tests, the module (at least pretend to) do not care about how java is available… But I think it is less spaghetti to add it to metadata.json that to install it manualy at some point in the acceptance test suite initialization?

**Comment by ghoneycutt** [comment]
There are a lot of open PR's for this module and after this sync occurs, rebasing will be very difficult for those contributors. Before merging this, suggest taking a pass through the PR's and merge as much as possible.

**Comment by smortex** [comment]
@ghoneycutt Thanks for helping sorting this out, I was focusing on this giant pile of work!  I rebased on top of master and cleaned the commits the best I could, but because of a lot of intricate changes it is not as readable as I would have liked it to be :cry:

I consider this ready for review now that CI is passing again in GitHub actions and without tests removal!

**Review by bastelfreak — APPROVED** [review]

**Comment by alexjfisher** [comment]
How confident are you with the rubocop changes? (It might be too much work now, but splitting rubocop fixes into at least safe autocorrect, unsafe autocorrect and manual fixes commits makes it *much* easier to review).
In the past, I may have gone a little overboard... https://github.com/voxpupuli/puppet-jenkins/pull/831 https://github.com/voxpupuli/puppet-jenkins/pulls?q=is%3Apr+author%3Aalexjfisher+is%3Aclosed+rubocop :)

**Comment by smortex** [comment]
> How confident are you with the rubocop changes?

Quite confident actually :smile: 

It is not visible due to commits cleanup and merging lots of `FIXUP` commits, but I incrementally adjusted the code until the test unit test suite pass, then fixed rubocop, then checked unit tests where still happy, then updated the voxpupuli-tests gem to fix more rubocop issues, then fixed the non-automatic fixable issues, and only when unit tests where green again attempted to fix the acceptance tests.

I tried to merge all related changes in single commits but the loads of changes induced by rubocop made it barely impossible to move the code at the correct location and some commits really deserved to be moved :-/. A trade-of was to merge some rubocop changes to have less conflicts to handle for moving these commits in history.

8852a0bab3bd43571e07297f1772943e1a78479c is mostly automatic changes before voxpupuli-test update
efcc297b77f729ab6658201070149fb40f8805af is mostly manual changes after the update

**Review by bastelfreak — APPROVED** [review]

**Pull request merged**
